export const events = [
  {
    slug: "react-ecosystem-live",
    image: "/images/event1.png",
    title: "React Ecosystem Live",
    location: "San Jose, CA",
    date: "March 21, 2024",
    time: "9:30 AM - 6:00 PM",
  },
  {
    slug: "nextjs-connect",
    image: "/images/event2.png",
    title: "Next.js Connect",
    location: "Dallas, TX",
    date: "April 28, 2024",
    time: "10:00 AM - 5:30 PM",
  },
  {
    slug: "modern-js-expo",
    image: "/images/event3.png",
    title: "Modern JavaScript Expo",
    location: "Brooklyn, NY",
    date: "May 16, 2024",
    time: "9:00 AM - 7:00 PM",
  },
  {
    slug: "ai-buildathon",
    image: "/images/event4.png",
    title: "AI Buildathon 2024",
    location: "Redmond, WA",
    date: "June 21–23, 2024",
    time: "48 Hours",
  },
  {
    slug: "decentralized-web-meet",
    image: "/images/event5.png",
    title: "Decentralized Web Meetup",
    location: "Tampa, FL",
    date: "July 26, 2024",
    time: "6:00 PM - 9:30 PM",
  },
  {
    slug: "fullstack-engineering-days",
    image: "/images/event6.png",
    title: "Full-Stack Engineering Days",
    location: "Boulder, CO",
    date: "August 19, 2024",
    time: "9:00 AM - 6:30 PM",
  },
  {
    slug: "devops-scale",
    image: "/images/event1.png",
    title: "DevOps at Scale",
    location: "Madison, WI",
    date: "September 11, 2024",
    time: "8:30 AM - 5:30 PM",
  },
  {
    slug: "mobile-first-summit",
    image: "/images/event2.png",
    title: "Mobile-First Summit",
    location: "Irvine, CA",
    date: "October 24, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "secure-systems-conf",
    image: "/images/event3.png",
    title: "Secure Systems Conference",
    location: "Cambridge, MA",
    date: "November 9, 2024",
    time: "8:00 AM - 6:30 PM",
  },
  {
    slug: "data-driven-hackfest",
    image: "/images/event4.png",
    title: "Data-Driven Hackfest",
    location: "Irvine, CA",
    date: "December 13–15, 2024",
    time: "72 Hours",
  },
  {
    slug: "cloud-infra-meetup",
    image: "/images/event5.png",
    title: "Cloud Infrastructure Meetup",
    location: "Salem, OR",
    date: "January 22, 2025",
    time: "6:30 PM - 9:00 PM",
  },
  {
    slug: "frontend-collective",
    image: "/images/event6.png",
    title: "Frontend Collective 2025",
    location: "Knoxville, TN",
    date: "February 21, 2025",
    time: "9:00 AM - 5:30 PM",
  },
];
